# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Pet Reminder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pet Reminder

pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'MessageKit'
pod 'Alamofire', '~> 5.6'

end
